### ISSUE TITLE
swiftmailer/swiftmailer false positive?

### ISSUE THREAD

**Issue by ostrolucky** [icanhazstring/composer-unused#10]
Can somebody confirm this? We use Swift_Mailer typehint in __construct and despite that it's marked as unused.

**Comment by icanhazstring** [comment]
Can you provide your `composer.json` and a code snippet where this is used?
Then I can see what is going wrong.

**Comment by ostrolucky** [comment]
I don't really want to get too deep debugging this before I get confirmation from other people

**Comment by xuanquynh** [comment]
@icanhazstring 
I believe that the reason is `swiftmailer/swiftmailer` package uses production autoload files by itself. See [swiftmailer composer.json](https://github.com/swiftmailer/swiftmailer/blob/master/composer.json) for more details.

When requiring `swiftmailer/swiftmailer` package as a dependency, composer ignores "autoload-dev" from that package and we only get this section:

```json
"autoload": {
    "files": ["lib/swift_required.php"]
},
```

Therefore, `PackageSubject` gets data from "autoload" only and can not detect the provided namespace `Swift_`. See the code [here](https://github.com/icanhazstring/composer-unused/blob/85ac5a24edd6d74e0918d2116400894c45a3302a/src/Subject/PackageSubject.php#L19)!

**Comment by icanhazstring** [comment]
Uh wow. Thats a hard one.
Maybe I can scan the dev autoload as well, as there is the `Swift_` namespace provided.
But I can't analyse the namespace from `files` or `classmap` directives.

**Comment by xuanquynh** [comment]
Swiftmailer is too old and doesn't follow psr-0 or psr-4 for production.
There may be some packages similar to it.
I can't also think of a solution right now. :cry:

**Comment by icanhazstring** [comment]
Just release version `0.3.0` to address this kind of issue.
If the problem persists let me know.

Closing it for now :)
